services:
  es-master:
    image: elasticsearch:8.6.2
    container_name: es-master
    # environment:
      # - "ELASTIC_PASSWORD=testing1"  # Set your Elasticsearch password
      # - "xpack.security.enabled=true"
      # - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"  # Elasticsearch HTTP port
      - "9300:9300"  # Elasticsearch internal communication

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es-master:9200"
      # - "ELASTIC_PASSWORD=testing1"  # Same as Elasticsearch password
      # - "ELASTIC_USERNAME=elastic"
    ports:
      - "5601:5601"  # Kibana port
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    depends_on:
      - es-master

  logstash:
    image: logstash:8.6.2
    container_name: logstash
    environment:
      - "ELASTICSEARCH_HOST=es-master"  # Elasticsearch service name
      # - "ELASTIC_PASSWORD=testing1"  # Same as Elasticsearch password
      # - "ELASTIC_USERNAME=elastic"
    volumes:
      # - ./suru-test/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      # - ./suru-test/logstash.conf:/usr/share/logstash/config/logstash.yml
      - ./app-logs/:/usr/share/applogs
    command: ["logstash", "-f", "/usr/share/applogs/logstash.conf"]  # This points to your config

volumes:
  es-data:
    driver: local
