# Dockerfile for Logstash
FROM logstash:8.6.2

# Create the /usr/share/applogs directory
RUN mkdir -p /usr/share/applogs \
    && chmod 777 /usr/share/applogs

# Add any other necessary configurations
